### ISSUE TITLE
Backlink

### ISSUE THREAD

**Issue by navanithpk** [CoVolNet/CoVolNet#4]
- [x] The covolnet volunteer registration form needs to have a hyperlink to index.html

**Comment by yadhu98** [comment]
@sheminanto Its time to create backend,meanwhile I will do the link backwards to the homepage.

**Comment by yadhu98** [comment]
@navanithpk backward link can only be added after connecting to the database.So first we can do that.

**Comment by navanithpk** [comment]
@yadhu98 Now that Shemin has shown me a working preview of the database in Heroku, can we connect the database to the frontend?

**Comment by yadhu98** [comment]
Issue resolved
